# Patch COLMAP's installed colmap-targets.cmake to fix FLANN library reference
#
# Problem: CMake's install(EXPORT) serializes the 'flann' INTERFACE IMPORTED target
#          as just "flann" which resolves to -lflann at link time.
#          vcpkg installs FLANN as libflann_cpp_s.a (static), not libflann.so
#
# Solution: After COLMAP install, patch colmap-targets.cmake to replace
#          the bare 'flann' reference with the actual library path.
#
# Required variables (set via -D):
#   COLMAP_INSTALL_DIR - Path to COLMAP installation (e.g., build/install/colmap)
#   FLANN_LIBRARY_PATH - Full path to FLANN library (e.g., .../libflann_cpp_s.a)

if(NOT DEFINED COLMAP_INSTALL_DIR)
    message(FATAL_ERROR "COLMAP_INSTALL_DIR must be defined")
endif()

if(NOT DEFINED FLANN_LIBRARY_PATH)
    message(FATAL_ERROR "FLANN_LIBRARY_PATH must be defined")
endif()

# Find colmap-targets.cmake
set(TARGETS_FILE "${COLMAP_INSTALL_DIR}/share/colmap/colmap-targets.cmake")

if(NOT EXISTS "${TARGETS_FILE}")
    message(WARNING "colmap-targets.cmake not found at ${TARGETS_FILE}, skipping patch")
    return()
endif()

file(READ "${TARGETS_FILE}" CONTENT)

# Check if already patched
if(CONTENT MATCHES "FLANN_PATCHED")
    message(STATUS "colmap-targets.cmake already patched for FLANN")
    return()
endif()

# The exported targets file contains INTERFACE_LINK_LIBRARIES with "flann" as one entry
# We need to replace this bare "flann" with the full library path
# The pattern in colmap-targets.cmake looks like:
#   INTERFACE_LINK_LIBRARIES "...;flann;..."

# Replace standalone "flann" (as a list element) with the full library path
# Be careful to only replace the bare word, not "flann_cpp" or similar
string(REGEX REPLACE
    ";flann;"
    ";${FLANN_LIBRARY_PATH};"
    CONTENT "${CONTENT}"
)

# Also handle case where flann is at the start or end of the list
string(REGEX REPLACE
    "\"flann;"
    "\"${FLANN_LIBRARY_PATH};"
    CONTENT "${CONTENT}"
)

string(REGEX REPLACE
    ";flann\""
    ";${FLANN_LIBRARY_PATH}\""
    CONTENT "${CONTENT}"
)

# Handle case where flann is the only entry (unlikely but possible)
string(REGEX REPLACE
    "\"flann\""
    "\"${FLANN_LIBRARY_PATH}\""
    CONTENT "${CONTENT}"
)

# Add marker to prevent re-patching
string(REPLACE
    "# Generated by CMake"
    "# Generated by CMake\n# FLANN_PATCHED: Replaced 'flann' with full library path"
    CONTENT "${CONTENT}"
)

file(WRITE "${TARGETS_FILE}" "${CONTENT}")
message(STATUS "Patched ${TARGETS_FILE}: replaced 'flann' with ${FLANN_LIBRARY_PATH}")
